### ISSUE TITLE
EPIC: oscal-tools site and repository maintenance

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#1088]
# User Story:

This is a tracking Issue for work in the oscal-tools repository https://github.com/usnistgov/oscal-tools

## Goals:

Short term, ready any time, with no (known) blockers:
- [x] https://github.com/usnistgov/oscal-tools/pull/29
- [x] Issue review and triage

(Also any other PRs in the OSCAL-Tools site:  https://github.com/usnistgov/oscal-tools/pulls)

Longer term strategic policy:

https://github.com/usnistgov/oscal-tools/issues/25

Spinoff issues to be developed here.

## Dependencies:

None known. Planning and determining dependencies is part of this Issue.

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by david-waltermire-nist** [comment]
@wendellpiez Will review the [issues](https://github.com/usnistgov/oscal-tools/issues) in the OSCAL tools repo and identify any issues that could be closed.

**Comment by wendellpiez** [comment]
@david-waltermire-nist could we carve out a few minutes to address permissions issues on the oscal-tools and/or other repositories? Thanks! (I also have a couple of policy/practice questions I could pose.)

Without Edit Labels at the bottom I can't add or remove Labels (and the same on other repositories).

![image](https://user-images.githubusercontent.com/1588228/154529042-d4f77cd3-7d54-4405-bd24-c14d05190b17.png)

**Comment by wendellpiez** [comment]
btw "closable" appears in the pulldown above (screenshot from my browser) on the OSCAL repo, but the OSCAL Tools repo, where I need it, has no "closable" Label yet ...

**Comment by wendellpiez** [comment]
A label having now been added, I have finished with this. 6/14 Issues marked as closable. Others represent work to be done or for discussion.

Let's schedule a time to review the outstanding oscal-tools Issues? Then we can check the box above as "complete" and proceed on that basis.

**Comment by david-waltermire-nist** [comment]
Discussed this on the NIST team status call on 3/3. This work has been completed.
