### ISSUE TITLE
OSCAL Catalog/Profile Editing Tool (Tracker-Issue)

### ISSUE THREAD

**Issue by JustKuzya** [usnistgov/OSCAL#1117]
# User Story:

As OSCAL adopting security professional I need to author/tailor OSCAL catalog/profile to the needs of my project/system/organization. I need to modify catalog structure, content, and control grouping to reflect the actual needs. The results should be saveable as profile. (Possibly as modified catalog)

## Goals:

This is an Epic-level plug-in tracker issue for the OSCAL Catalog Authoring Tool. The tool has to implement the following features:

### Currently in planning and development features

- ~~[ ] Add drag-n-drop functionality to regrouping UI~~
- [ ] Find and incorporate markdown editor for statements editing in the edit-controls UI
- [ ] Perform AJV validation for the assembled JSON document before allowing user to save it locally   
- [ ] Perform AJV validation for the user-uploaded JSON documents to address possible validation problems before they cause exception in the application.  

## Acceptance Criteria

- [ ] OSCAL Catalog Authoring Tool allows to pick and edit controls catalog expressed in OSCAL
- [ ] CA Tool provides an easy UI for selecting existing baselines as a preliminary tailoring step
- [ ] CA Tool has documentation for development environment [setup, building](https://github.com/usnistgov/oscal-cat/issues/3), and deployment procedures 
- [ ] CA Tool has [user documentation for at least the most frequently used parts with explained alternative choices](https://github.com/usnistgov/oscal-cat/issues/5)
- [ ] [Clean up CA Tool dependencies](https://github.com/usnistgov/oscal-cat/issues/4) to minimize known vulnerabilities

**Comment by aj-stein-nist** [comment]
Closing as obsolete. This project was archived as of https://github.com/usnistgov/oscal-cat/commit/be67759cc192e7af37cecd5d200760b6316dec61 and work on that project paused.
