### ISSUE TITLE
[EPIC] CI/CD Enhancements

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/OSCAL#1180]
# User Story:

As an OSCAL developer, in order to have a quick and seamless experience with development and testing of the official OSCAL repos' content and software, I would like enhancements to the OSCAL CI/CD systems to: simplify the build process with a single command, facilitate automated releases, and improve the modularity of different build steps.

## Goals:

- [ ] New functionality to auto-increment all OSCAL artifacts and automate as much as possible for steps to create a new release
- [ ] Reach consensus and implement a tool to unify all build steps (i.e. `make`)
  - [ ] Potentially unify and clean up the different usages of XProc for local dev, but not for CI/CD pipelines for a lot of tooling that is in the hot-path of building artifacts in CD (Metaschema bootstrapping, OSCAL schema generation, content generation, et cetera) 
- [ ] Update tooling, documentation, and maybe team workflow to use `docker` within GitHub Actions like we should be doing with `docker-compose` on our laptops; without this, we have two very similar but different execution pipelines (with shell scripts in local workstation testing but separate YAML declaration for the GitHub Actions job)

## Dependencies:

{Describe any previous issues or related work that must be completed to start or complete this issue.}

**Comment by aj-stein-nist** [comment]
Also for consideration:
- Adding, changing, or removing how certain steps in GitHub Actions to increase performance the CI/CD process (i.e. uploader action steps take sometimes minutes for uploading artifacts).
- Exposing all dependency management manifests to ensure everything is checked and vulnerable packages reported (as part of #1008)

**Comment by aj-stein-nist** [comment]
Interesting opportunity for improved tooling. Not part of the list yet, but for potential inclusion: usnistgov/OSCAL#1183.

**Comment by aj-stein-nist** [comment]
Also, given discussion today with [release ZIP archive JSON Schema files and source code pulls not working as planned](https://gitter.im/usnistgov-OSCAL/Lobby?at=623b575fddcba117a236f491), consider some integration-level tests around sanity-checking released contents and warning when they do not work as expected? Talk to Dave about this for future releases.

**Comment by aj-stein-nist** [comment]
@aj-stein-nist needs to review the list of work items in this epic for those that are obsolete, change and remove the applicable ones. Some still appear to have value and worth considering (specifically: how do we auto-increment models for release).
