### ISSUE TITLE
Automatically Add New Issues to Issue Triage Projects for Developer Review

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/OSCAL#1209]
# User Story:

As a NIST staff OSCAL developer, in order to ensure I can quickly review and keep current on newly added issues from colleagues or active community members, I would like to have any new issue automatically added to the Issue Triage Project and its Needs Triage column automatically so I do not have to do so manually and potentially risk making mistakes.

## Goals:

We had an action item from previous issue triage meetings to review why GitHub does not automatically add news issues to the Needs Triage column of respective Issue Triage project boards. Automation can only occur for columns, but no out of the box automation in GitHub will add them to the project for you. The wording of the automatic kanban projects implies this gap.

![image](https://user-images.githubusercontent.com/94922603/163876444-209cae0e-d601-4af7-a3d6-a4945de6c8ac.png)

This feature is a known [sticking point and heavily requested, but users and staff recommend using GH Actions to implement this](https://github.community/t/new-issues-not-being-auto-added-to-project-board/904/24).

If done properly, this automation will simply take any new issue and add it to the respective project board (if it exists). From previous discussion, we will not consider additional automation regarding other state transitions in the triage process for automation. That is out of scope. A new GitHub Actions workflow will focus on only adding to the initial addition.

If done properly, _existing issues will not be modified_, especially given OSCAL's sizable backlog.

## Dependencies:

N/A at this time.

## Acceptance Criteria

- [x] Add issue triage workflow automation to the relevant repos, at this time (on `main`/`master` branch to make immediately active):
  - [X] usnistgov/OSCAL (usnistgov/OSCAL#1210)
  - [X] usnistgov/oscal-content (usnistgov/oscal-content#102)
  - [x] usnistgov/metaschema (usnistgov/metaschema#206)
  - [x] usnistgov/oscal-tools (usnistgov/oscal-tools#53)
- [x] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [x] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.
- ~All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.~

**Comment by aj-stein-nist** [comment]
@david-waltermire-nist per our conversation, I updated the three remaining PRs with the trailing newline, the way it should be (sorry I spaced out on that). They should be ready for merge and review as you deem fit.

**Comment by aj-stein-nist** [comment]
@david-waltermire-nist are we going to merge the other related PRs in oscal-content and oscal-tools before closing closing this or would want me to not make that part of the acceptance criteria bullets above in the original issue description?
