### ISSUE TITLE
.NET Library for Metaschema and OSCAL (Tracker)

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/OSCAL#1279]
# Epic Summary:

As an OSCAL tool developer, in order to quickly make tools with the .NET Framework and .NET Core ecosystems, I want one or more libraries I can use as a part of my own tools that will help me in serializing, de-serializing, and transforming objects in .NET runtimes marshalled from source OSCAL JSON/XML/YAML objects.

## Goals:

NOTE: This is a public tracker issue for the NMetaschema ([nmetaschema](https://github.com/usnistgov/nmetaschema)) and NOSCAL (TBD) libraries being developed by the NIST team. If you are interested in having pre-release and pre-publication access to this repository prior to open-sourcing it, please comment on this issue and request the NIST OSCAL team vet and review your access.

These libraries will have a modular, hierarchical architecture much like that of [`metaschema-java`](https://pages.nist.gov/metaschema-java/), [`liboscal-java`](https://github.com/usnistgov/liboscal-java/) and [`oscal-cli`](https://github.com/usnistgov/oscal-cli), but the .NET ecosystem.

Goals of the projects and libraries:

- Converting OSCAL content between the OSCAL XML, JSON, and YAML formats.
- Validating an OSCAL resources to ensure it is well-formed and valid.
- Validating a Metaschema model definition to ensure it is well-formed and valid.
- Generating XML and JSON Schemas from a Metaschema model definition.
- Support the key functionalities above for the .NET ecosystem, meaning for .NET Core and the traditional .NET Framework runtimes
- Potentially resolving OSCAL profiles (although this is a stretch goal at this time)

## Dependencies:

- [ ] Completion of review and publication procedures for CSD/ITL/NIST as identified by the NMetaschema [OSS Publication Ready](https://github.com/usnistgov/nmetaschema/milestone/3) milestone.

### NMetaschema

- [ ] [[EPIC] Metaschema Object Model](https://github.com/usnistgov/nmetaschema/issues/3)
  - [x] [Review `metaschema-java` and document class hierarchy design.](https://github.com/usnistgov/nmetaschema/issues/7)
  - [ ] [Review `metaschema-java`, design, and implement base abstract classes.](https://github.com/usnistgov/nmetaschema/issues/8)
  - [ ] [Review `metaschema-java` interfaces, design, and implement interfaces.](https://github.com/usnistgov/nmetaschema/issues/9)
  - [ ] [Determine effective unit testing and test coverage methods for abstract base classes and interfaces.](https://github.com/usnistgov/nmetaschema/issues/10)
- [ ] [Research and determine documentation systems for core libraries.](https://github.com/usnistgov/nmetaschema/issues/11)
- [ ] [Initialize Repo Tooling and Setup](https://github.com/usnistgov/nmetaschema/issues/12)
- [ ] [Automated unit testing](https://github.com/usnistgov/nmetaschema/issues/14)
- [ ] [Linting and code smell checks](https://github.com/usnistgov/nmetaschema/issues/15)
- [ ] [Static code analysis](https://github.com/usnistgov/nmetaschema/issues/16)
- [ ] [Complexity checking? (Nice to want, maybe not necessary to have?)](https://github.com/usnistgov/nmetaschema/issues/17)
- [ ] [Additional checks that may be needed?](https://github.com/usnistgov/nmetaschema/issues/18)
- [ ] [[EPIC] Metaschema XML Parser](https://github.com/usnistgov/nmetaschema/issues/4)
- [ ] [[EPIC] Metaschema C# Binding](https://github.com/usnistgov/nmetaschema/issues/5)
- [ ] [[EPIC] C# Code Generator](https://github.com/usnistgov/nmetaschema/issues/6)
- [ ] [[EPIC] Production Release Readiness (MIDAS)](https://github.com/usnistgov/nmetaschema/issues/21)
  - [x] [Add Contribution Guidelines for Developers](https://github.com/usnistgov/nmetaschema/issues/22)

### NOSCAL

TBD for repo and issue creation. Will begin once sufficient progress made on NMetaschema.

**Comment by aj-stein-nist** [comment]
I need to determine a way to take the private board epics and their issues trackable on this board. Will look into it.

At the time of this writing, I am working on the abstract base classes and a large number of interfaces. I worked on structuring non-functional requirements to meet NIST requirements for publication and open-sourcing this library formally.

More to come, and specific trackable task items for the community to review and request alpha/beta access to the code prior to open-sourcing.

**Comment by aj-stein-nist** [comment]
I found a quick and dirty way to use `gh` and `jq` to quickly format and convert the GitHub issues into a Markdown list.

```
gh issue list --json  title,number | jq -s -c '.[] | sort_by(.number)' | jq -r '.[] | "- [ ] [\(.title)](https://github.com/usnistgov/nmetaschema/issues/\(.number))"'
``` 

[It is also in gist form for reusability](https://gist.github.com/aj-stein-nist/cc94f630df835a77b7a52cc77c7792f9).

**Comment by aj-stein-nist** [comment]
> I would like to upvote this issue as a.NET library -- preferably a NuGet package -- will make my life considerably easy. If possible, I would like to contribute to this issue as well.

1. Definitely interesteded in NuGet registry publication, be it via [the official NuGet Gallery registry](https://nuget.org) _or_ publication in a public NuGet registry [via GitHub Packages](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-nuget-registry). There are (NIST's) organizational reasons to consider the latter. In either case, this would be part and parcel of [[EPIC] Production Release Readiness (MIDAS)](https://github.com/usnistgov/nmetaschema/issues/21). NIST will require either registry certain standards met before general _open_ release to the public.
2. I have discussed contribution with our supervisor and will need to set up contribution guidelines. Once we have merged those in and taken care of the formalities, I will loop you in. Hopeful ETA is some time next week. :-)

**Comment by aj-stein-nist** [comment]
@hahsanti with usnistgov/nmetaschema#22 with a contribution guide and code of conduct up, I can move forward on inviting you in for collaboration. Let me know a good time you are available to discuss this week, bring you up to speed, and discuss methods to facilitate shared development on this library. Welcome to my crew!

**Comment by aj-stein-nist** [comment]
> @aj-stein-nist if it is okay, I will connect with you on Gitter.

@hahsanti thanks for meeting today. I will give you some time to review the current WIP code, design, and initial architecture. We can meet up next week and plan potential involvement in the future. Thanks for your interest and time investment thus far.

**Comment by IvanDrag0** [comment]
I'd like to contribute to the effort, if possible.

**Comment by aj-stein-nist** [comment]
> I'd like to contribute to the effort, if possible.

I think I can add you soon, best case tomorrow or worst case early next week. If you do not hear from me by Monday, feel free to follow up.

**Comment by aj-stein-nist** [comment]
> I'd like to contribute to the effort, if possible.

@IvanDrag0, let's set up some time this coming week to discuss interest level, expectations, and a possible working arrangement.

**Comment by aj-stein-nist** [comment]
@hahsanti, how are things going with you? We should sync up as well. Maybe to start, separately of IvanDrag0, but eventually maybe we find a time to meet as a unified group.

**Comment by IvanDrag0** [comment]
> > I'd like to contribute to the effort, if possible.
> 
> @IvanDrag0, let's set up some time this coming week to discuss interest level, expectations, and a possible working arrangement.

@aj-stein-nist Sure thing. Let me know when it works for you and how you'd like to meet up.

**Comment by Ikendiken** [comment]
I'm excited to see work started on dotnet tooling for OSCAL. How can I get involved?

**Comment by aj-stein-nist** [comment]
> I'm excited to see work started on dotnet tooling for OSCAL. How can I get involved?

Typically, we like to meet up, discuss your desired level of participation (active/passive consumer of libraries once published in GitHub packages, we're a waaaays away from that), and contribution requirements (we remind you of our license and public domain).

Let us know if/when you would like to talk and we can move forward. :-)

**Comment by aj-stein-nist** [comment]
> I'm excited to see work started on dotnet tooling for OSCAL. How can I get involved?

@Ikendiken are you still interested in meeting soon to discuss engagement and participation?

**Comment by DavidAllardyce** [comment]
@aj-stein-nist Indeed. I'll reach out on gitter today.

**Comment by hahsanti** [comment]
@Ikendiken @aj-stein-nist, did y'all meet then? I have been travelling for work, but I am back and I would like to start contributing to this work.

**Comment by aj-stein-nist** [comment]
> @Ikendiken @aj-stein-nist, did y'all meet then? I have been travelling for work, but I am back and I would like to start contributing to this work.

Hi @hahsanti. Yes we did! We just synced up on expectations and future. @Ikendiken did review the PR an I need to work his feedback, but we have not committed to anything specific yet. I will keep him and you in the loop of future development efforts and offer you alpha/beta access. Sound good?

**Comment by IvanDrag0** [comment]
@aj-stein-nist Is the effort to create an OSCAL .NET library still ongoing? I'm finally done with classes so I can start dedicating more time to this but I can't seem to find the repo (even though I'm pretty sure you've invited me to it before).

**Comment by AdamOlineDOJ** [comment]
@aj-stein-nist I'd like to request access to the repository. We have another resource here, Hamza Choudhury, who will post a similar request as well. We're very interested in contributing to the .NET Library, in support of our efforts at DOJ on CSAM and OSCAL.

**Comment by IvanDrag0** [comment]
@hahsan-ti It looks like on of the projects that @aj-stein-nist showed me but I could have sworn there was some C# code there (unless I've missed it or it was removed).

**Comment by hahsan-ti** [comment]
> @hahsan-ti It looks like on of the projects that @aj-stein-nist showed me but I could have sworn there was some C# code there (unless I've missed it or it was removed).

There is a branch called `9-review-metaschema-java-interfaces-design-and-implement-interfaces` in the repo, owned by @aj-stein-nist.

**Comment by IvanDrag0** [comment]
@hahsan-ti Thank you! Can't believe I missed it.

**Comment by nikitawootten-nist** [comment]
Hi all, I'm excited to see renewed interest in this issue. @aj-stein-nist is out this week, but I'm sure he'll be able to provide a update when he's back.

**Comment by aj-stein-nist** [comment]
> Hi all, I'm excited to see renewed interest in this issue. @aj-stein-nist is out this week, but I'm sure he'll be able to provide a update when he's back.

Hello everyone, sorry for the delayed reply. As individual and project priorities have shifted, I have not made significant progress on this library in the last six months.

As a prerequisite to this work and separate from it, I had been working with David Waltermire, Nikita, and Wendell to improve my understanding of Metaschema and coordinate with them for this to result in more expansive Metaschema documentation. There is a lot of work to that (and I am small support actor in that cast), but that necessarily had to happen to the detriment of this work.

If those comment on this issue would like to plot a course on the way forward with our team and make it more inclusive, I am very supportive of that. @IvanDrag0, I can add you as you wish.

**Comment by IvanDrag0** [comment]
@aj-stein-nist I'd appreciate the add!

**Comment by aj-stein-nist** [comment]
This work had stalled as other priorities came up like #1281 we will need to review the publication process and how to allow public collaboration or development with less effort so the community can pick up the work without immediate communication with the community. On that note, marking as further analysis needed.

**Comment by aj-stein-nist** [comment]
Work on the core Metaschema .NET library has long since paused but may resume in the near future. Now that there is cleaner delineation between [Metaschema and core OSCAL projects](https://pages.nist.gov/OSCAL/about/projects/) this issue does not really belong here and we do not use tracker issues anymore anyway (GitHub's projects and embedded issue lists have vastly improved since this issue was created. If further progress was to happen later, it will happen in [my relocated copy](https://github.com/aj-stein-nist/nmetaschema). I am closing this issue now.
