### ISSUE TITLE
Address OSCAL and Metaschema Java library defects

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/OSCAL#1282]
# User Story:

As a user of the [Metaschema Java](https://github.com/usnistgov/metaschema-java/) and [OSCAL Java](https://github.com/usnistgov/liboscal-java/) libraries, I need know defects to be repaired. I also need the OSCAL Java library to be updated to the latest OSCAL release.

## Goals:

The following issues need to be addressed for the next release of the OSCAL Java library:

- [x] Dependencies need to be updated
- [x] Change stream autoclose behavior. See https://github.com/EasyDynamics/oscal-rest-service/pull/91#discussion_r870748860
~~- [ ] usnistgov/liboscal-java#3~~
~~- [ ] usnistgov/liboscal-java#5~~
~~- [ ] usnistgov/liboscal-java#6~~
- [x] usnistgov/liboscal-java#12
   - [x] Add mechanism to allow overriding URL resolution behavior. See https://github.com/usnistgov/metaschema-java/pull/28.
   - [x] Ensure new mechanism is used whenever a URL is resolved. See https://github.com/usnistgov/liboscal-java/pull/20.
~~- [ ] usnistgov/liboscal-java#13~~
- [x] usnistgov/liboscal-java#14
- [x] usnistgov/liboscal-java#15. See https://github.com/usnistgov/liboscal-java/pull/21.
- [x] usnistgov/liboscal-java#17
- [x] usnistgov/liboscal-java#19

## Dependencies:

None.

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by david-waltermire-nist** [comment]
Issues have been resolved an will be released with the liboscal-java [v1.0.4 release](https://github.com/usnistgov/liboscal-java/milestone/1).
