### ISSUE TITLE
Automatically Remove Issues from Triage Board When Closed

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/OSCAL#1302]
# User Story:

As a NIST OSCAL developer, in order to improve efficiency and reduce impact on developer bandwidth to perform ongoing triage of issues, I would like to have improved automation to remove the card [from the Issue Triage board](https://github.com/usnistgov/OSCAL/projects/52) once its issue has been closed as complete.

## Goals:

This had been discussed internally with Dave and the NIST OSCAL dev team. This work is a continuation of usnistgov/OSCAL#1209. We now automatically bring in issues to the triage board, it is now time to balance this out and make sure they get removed.

## Dependencies:

N/A

## Acceptance Criteria

- [x] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [x] Add issue triage workflow automation to the relevant repos, at this time (on `main`/`master` branch to make immediately active):
  - [x] usnistgov/OSCAL (usnistgov/OSCAL#1303)
  - [x] usnistgov/oscal-content (usnistgov/oscal-content#111)
  - [x] usnistgov/metaschema (usnistgov/metaschema#210)
  - [x] usnistgov/oscal-tools (usnistgov/oscal-tools#55)
- [x] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}
