### ISSUE TITLE
XSLT Metaschema support update and unit tests

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#1323]
In the Metaschema repository, there is ongoing work to finalize the Metaschema model, and to harmonize its implementations going forward.

This is a tracking Issue for work on the XSLT M4 Metaschema implementation, making it ready to deploy supporting OSCAL assuming a complete v1.0 Metaschema implementation (for schema and converter generators).

## Goals:

- [x] usnistgov/metaschema#195 with PR addressing it
- [x] usnistgov/metaschema#169 with PR addressing it
- [x] usnistgov/metaschema#212 with PR addressing it
- [x] #1338

## Related / Dependencies

Unit tests demonstrating functionality belong in both the `metaschema-xspec` and `schema-generation` folders of `testing` (in that repo). See usnistgov/metaschema#186

Potentially related: usnistgov/metaschema#201, usnistgov/metaschema#202

NOT IN SCOPE: extending functionality to new areas e.g. constraint testing

## Acceptance Criteria

- [ ] Appropriate commits have been made in usnistgov/metaschema repository
- [ ] Commits include unit tests showing stability and protecting against regressions
- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.
