### ISSUE TITLE
Develop a solution for managing identifier clashes in OSCAL Profiles

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/OSCAL#1397]
### User Story

As an OSCAL Profile author or consumer, I need a means to resolve identifier clashes caused by importing catalog content from different sources, whose objects have the same identifier for different objects. The approach that is used must be deterministic and must preserve the provenance of the original identifiers.

A solution must be able to support:
- [x] Renaming specific identifiers by specifying an old and new name. Resolved by usnistgov/OSCAL#1424.
- [x] Applying a prefix and/or suffix supporting bulk renaming. Resolved by usnistgov/OSCAL#1428.
- [x] Recording the original identifier for a given object. Resolved by usnistgov/OSCAL#1423.

Conflicts may occur in controls, groups, parts, and parameters.

This issue will develop a solution to address the following issues:
- #538 -> PR #1196
- #843
- #1327

Follow on work needs to include:

- [x] Document `source-identifier` in the profile resolution specification based on the changes in PR usnistgov/OSCAL#1423.
- [ ] #1474

### Goals

- [ ] Feature PR usnistgov/OSCAL#1424 has been updated to include all additional PRs contributing to this feature set.
   - [ ] Merged PR usnistgov/OSCAL#1423.
- [ ] Design and document an approach to update the Profile model that will address the requirements above.
   - [ ] Documented approach is backwards compatible with OSCAL 1.x models.
- [ ] Develop a few examples that illustrate use of the features identified above and publish these examples as GitHub gists.
- [ ] Create issues for any follow on work to be addressed.

Issue #1398 will be used to socialize the design with the OSCAL community.

### Dependencies

None.

### Acceptance Criteria

- [ ] New design document is publicly available
- [ ] Examples are published publicly
- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by Compton-NIST** [comment]
> Summary to address the third requirement: "Recording the original identifier for a given object."

### This solution is an approach to handling identifier conflicts by:
- **Req 3:** Recording the original identifier for a given object.

The draft specification profile model supports `from` and `to` mapping, but the catalog model needs to track the `from` identifier to maintain a record of the original identifier for traceability.

## Proposed Solution

The catalog model supports `props` which is capable of maintaining key/value information related to controls.  One possible solution that utilizes the existing major version of OSCAL (non-breaking) is to define a property as:

### Catalog Model

```
catalog [1]: {
    uuid [1]: uuid,
    metadata [1]: { … },
    params [0 or 1]: [ … ],
    controls [0 or 1]: [
        An array of control objects [1 to ∞] {
            id [1]: token,
            class [0 or 1]: token,
            title [1]: markup-line,
            params [0 or 1]: [ … ],
```
>            props [0 or 1]: [
>                An array of prop objects [1 to ∞] {
>                    name [1]: token,
>                    uuid [0 or 1]: uuid,
>                    ns [0 or 1]: uri,
>                    value [1]: string,
>                    class [0 or 1]: token,
>                    remarks [0 or 1]: markup-multiline,
>                }
>            ],
```
            links [0 or 1]: [ … ],
            parts [0 or 1]: [ … ],
            controls [0 or 1]: [ … ],
        }
    ],
# [...SNIP...]
```

### Catalog Sample


```xml
    <control class="SP800-53" id="au-6-low">
        <title>Audit Review, Analysis, and Reporting</title>
        <!-- [...SNIP...] -->

        <prop ns="http://csrc.nist.gov/ns/oscal"
            name="source-identifier" 
            value="au-6"/>

        <!-- [...SNIP...] -->  
    </control>
    <control class="SP800-53" id="au-6">
        <title>Audit Review, Analysis, and Reporting</title>
        <!-- [...SNIP...] -->
    </control>
```


![One Catalog, Two Profiles](https://user-images.githubusercontent.com/107055718/186236266-79868885-ee05-4a0a-8ef0-e6fce5a4295a.svg)

![Two Catalogs, One Profile](https://user-images.githubusercontent.com/107055718/186236276-94ad1c5f-d0f1-4356-8cf9-5854cc22f8d7.svg)

**Comment by Compton-NIST** [comment]
Prefix/Suffix requirement is documented in another issue: https://github.com/usnistgov/OSCAL/issues/1327
