### ISSUE TITLE
[RFC] Add a Calendar Feed for NIST OSCAL Events to OSCAL Site?

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/OSCAL#1408]
### User Story

As an OSCAL stakeholder and active community member, in order to have a more consistent way to keep abreast of any OSCAL event (dev lunch, model meeting, and mini workshops), I want a hosted calendar to automatically update my email/calendar management client. I also want to know what others think of this, so this is currently a Request for Comment (RFC). :-)

### Goals

- [x] Pick up a technical solution to communicate calendar updates in one consistent, highly available  #1638
- [x] Communicate the use of the updated mechanism and develop a documented process for keeping the event calendar current and up to date #1638
- [x] Implement the change in the website with team support #1642

### Dependencies

- [x] Determination if just using site updates with usnistgov/OSCAL#1407 is sufficient or not, and if this work is prioritized or closed as work we do not plan to do.

### Acceptance Criteria

- [x] Design a solution with common community use cases in mind.
- [x] Implement the calendaring solution, if well-received.
- [x] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [x] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [x] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by GaryGapinski** [comment]
While proprietary, Google Calendar works quite well for me for a multiple calendar view. However, that is **not** the same as receiving calendar invitations and selectively choosing them to add to one of my personal calendars.

**Comment by aj-stein-nist** [comment]
> While proprietary, Google Calendar works quite well for me for a multiple calendar view. However, that is **not** the same as receiving calendar invitations and selectively choosing them to add to one of my personal calendars.

Absolutely, excellent point, Gary. The design intent of this would be, for Google's GMail/Workspaces, Office365/hosted Exchange and Outlook, and the macOS/iOS calendars, creating a publicly readable ICS-based calendar could allow people to 1) passively receive all invites and/or accept/reject calendar events onto your own personal calendar by copying/moving preferred events at your leisure.

A research note for us to pick up with that approach, if others encourage and the community wants it.

https://www.jvt.me/posts/2019/05/22/ical-events-hugo/

**Comment by david-waltermire-nist** [comment]
Maybe [Hugo templating](https://gohugo.io/templates/rss/) can be used to address this?

**Comment by aj-stein-nist** [comment]
I have been looking into this in relationship to #1604. Earlier in the week, I met with Michaela and Chris to discuss the viability of the CSRC CMS tool for managing the calendar. Michaela gave us a 30 minute demo around the pages functionality and some of the calendar functionality. It seems like it might not be a good fit, but a little more experimentation is needed given the ICS calendaring functionality it will give us for free.

**Comment by aj-stein-nist** [comment]
I tried the csrc.nist.gov CMS and it had a couple fundamental problems. The public NIST website doesn't seem ideal, but this shared calendar solution through Outlook seems to preliminarily serve most of our needs.

https://outlook.office365.com/calendar/published/553a60383771471381091ed979a954f6@nist.gov/aebfdc75f48a44a4a2588a54d4cd70308785621945585929004/calendar.html

https://outlook.office365.com/owa/calendar/553a60383771471381091ed979a954f6@nist.gov/aebfdc75f48a44a4a2588a54d4cd70308785621945585929004/calendar.ics

Further testing is needed and I might wrap it into the website and make a SOP for the rest of the team to use this approach for all event invites.

/cc @canb227 ;-)

**Comment by aj-stein-nist** [comment]
I have some updates and need to make a decision record and get buy-in and endorsement from the rest of the NIST OSCAL Team (because their opinion matters here a lot). I will need to complete that early in the next sprint.

**Comment by aj-stein-nist** [comment]
> I tried the csrc.nist.gov CMS and it had a couple fundamental problems. The public NIST website doesn't seem ideal, but this shared calendar solution through Outlook seems to preliminarily serve most of our needs.
> 
> https://outlook.office365.com/calendar/published/553a60383771471381091ed979a954f6@nist.gov/aebfdc75f48a44a4a2588a54d4cd70308785621945585929004/calendar.html
> 
> https://outlook.office365.com/owa/calendar/553a60383771471381091ed979a954f6@nist.gov/aebfdc75f48a44a4a2588a54d4cd70308785621945585929004/calendar.ics
> 
> Further testing is needed and I might wrap it into the website and make a SOP for the rest of the team to use this approach for all event invites.
> 
> /cc @canb227 ;-)

We deprecated the calendar mentioned above ☝️ in favor of a functional account in NIST parlance to run a calendar we can publish from (as HTML and ICS file) and integrate that into our public website. More to follow in a decision doc about the options tried, use case requirements not met, and this final recommendation from me I hope the team will appreciate.

Updated test calendars. Michaela has tested this for one of our next community meetings.

https://outlook.office365.com/owa/calendar/553a60383771471381091ed979a954f6@nist.gov/e72d2ca648dc4c3db7470fb7339674f211929765598025548039/calendar.html

https://outlook.office365.com/owa/calendar/553a60383771471381091ed979a954f6@nist.gov/e72d2ca648dc4c3db7470fb7339674f211929765598025548039/calendar.ics

**Comment by iMichaela** [comment]
> Updated test calendars. Michaela has tested this for one of our next community meetings.

@aj-stein-nist - I tested it with our team, I did not invite the entire community through this calendar. to not confuse people, and not force them to accept it again.  I will use the oscalevt@nist.gov calendar for all future events.

**Comment by aj-stein-nist** [comment]
> > Updated test calendars. Michaela has tested this for one of our next community meetings.
> 
> @aj-stein-nist - I tested it with our team, I did not invite the entire community through this calendar. to not confuse people, and not force them to accept it again. I will use the [oscalevt@nist.gov](mailto:oscalevt@nist.gov) calendar for all future events.

OK, thanks. I must have misread a stream of emails that came through as I was in between tasks. Thanks for testing it in any case.

**Comment by aj-stein-nist** [comment]
OK, I believe the next step is determining and documenting a SOP for handling calendar events to be completed before or alongside usnistgov/OSCAL#1642.

**Comment by aj-stein-nist** [comment]
AJ discussed this in the last status meeting, he will quickly draft a status meeting SOP to publish for staff. @iMichaela and @wendellpiez offered to review.

**Comment by aj-stein-nist** [comment]
Missed some stuff need to open this up for a little bit longer.
