### ISSUE TITLE
Fully Deploy OSCAL Metaschema Constraints

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/OSCAL#1530]
# Goals

- [ ] Design and implement a solution to manage core OSCAL constraints.
   - [ ] Ensure necessary Metaschema support for constraints
      - [x] Implement a recursion function to support indexing of identified objects in imported OSCAL content.
      - [ ] Ensure indexing supports detecting conflicting entries (#1290)
   - [ ] Define a model that simplifies the constraint definition process
      - [ ] Allow common index constraint definitions to be easily shared between models.
      - [ ] Allow allowed value sets to be defined and shared between models, without the need for using XML entities.
      - [ ] Support the association of specific property names with their allowed values.
      - [ ] Simplify definition of link constraints supporting both direct and resource references.
- [ ] Review existing constraints for all models
   - [ ] oscal_assessment-common_metaschema.xml
      - [ ] Ensure that all identifier cross-references are properly constrained
      - [ ] Ensure that all allowed values are properly constrained
      - [ ] Ensure that all data type restrictions are properly constrained
   - [ ] oscal_assessment-plan_metaschema.xml
      - [ ] Ensure that all identifier cross-references are properly constrained
      - [ ] Ensure that all allowed values are properly constrained
      - [ ] Ensure that all data type restrictions are properly constrained
   - [ ] oscal_assessment-results_metaschema.xml
      - [ ] Ensure that all identifier cross-references are properly constrained
      - [ ] Ensure that all allowed values are properly constrained
      - [ ] Ensure that all data type restrictions are properly constrained
   - [ ] oscal_catalog_metaschema.xml
      - [ ] Ensure that all identifier cross-references are properly constrained
      - [ ] Ensure that all allowed values are properly constrained
      - [ ] Ensure that all data type restrictions are properly constrained
   - [ ] oscal_complete_metaschema.xml
      - [ ] Ensure that all identifier cross-references are properly constrained
      - [ ] Ensure that all allowed values are properly constrained
      - [ ] Ensure that all data type restrictions are properly constrained
   - [ ] oscal_component_metaschema.xml
      - [ ] Ensure that all identifier cross-references are properly constrained
      - [ ] Ensure that all allowed values are properly constrained
      - [ ] Ensure that all data type restrictions are properly constrained
   - [ ] oscal_control-common_metaschema.xml
      - [ ] Ensure that all identifier cross-references are properly constrained
      - [ ] Ensure that all allowed values are properly constrained
      - [ ] Ensure that all data type restrictions are properly constrained
   - [ ] oscal_implementation-common_metaschema.xml
      - [ ] Ensure that all identifier cross-references are properly constrained
      - [ ] Ensure that all allowed values are properly constrained
      - [ ] Ensure that all data type restrictions are properly constrained
   - [ ] oscal_mapping_metaschema.xml
      - [ ] Ensure that all identifier cross-references are properly constrained
      - [ ] Ensure that all allowed values are properly constrained
      - [ ] Ensure that all data type restrictions are properly constrained
   - [ ] oscal_mapping-common_metaschema.xml
      - [ ] Ensure that all identifier cross-references are properly constrained
      - [ ] Ensure that all allowed values are properly constrained
      - [ ] Ensure that all data type restrictions are properly constrained
   - [ ] oscal_meta-constraints.xml
      - [ ] Ensure that all identifier cross-references are properly constrained
      - [ ] Ensure that all allowed values are properly constrained
      - [ ] Ensure that all data type restrictions are properly constrained
   - [ ] oscal_metadata_metaschema.xml
      - [ ] Ensure that all identifier cross-references are properly constrained
      - [ ] Ensure that all allowed values are properly constrained
      - [ ] Ensure that all data type restrictions are properly constrained
   - [ ] oscal_poam_metaschema.xml
      - [ ] Ensure that all identifier cross-references are properly constrained
      - [ ] Ensure that all allowed values are properly constrained
      - [ ] Ensure that all data type restrictions are properly constrained
   - [ ] oscal_profile_metaschema.xml
      - [ ] Ensure that all identifier cross-references are properly constrained
      - [ ] Ensure that all allowed values are properly constrained
      - [ ] Ensure that all data type restrictions are properly constrained
   - [ ] oscal_ssp_metaschema.xml
      - [ ] Ensure that all identifier cross-references are properly constrained
      - [ ] Ensure that all allowed values are properly constrained
      - [ ] Ensure that all data type restrictions are properly constrained

**Comment by aj-stein-nist** [comment]
As an epic predating usnistgov/OSCAL#1688 board reorganization, I will want to label this as needs refinement for now until it can be broken down, rescoped, and or closed.
