### ISSUE TITLE
Document an OSCAL project roadmap and related team artifacts

### ISSUE THREAD

**Issue by brianrufgsa** [usnistgov/OSCAL#183]
# User Story:

As a new OSCAL team member, I can understand the guiding principles, team policy/agreements, and project roadmap.

There have been several points discussed by the team to which team members have verbally agreed. New team members have no way to know this. The agreements should be documented so that new team members can be aware of them, and in case the agreements are not remembered accurately in the future.

Likewise, all project members should be clear on how current and up-coming sprints fit into the big picture.

## Goals:

1. Define a location to store project dynamics.

2. Capture, document, and publish project execution principles, 

3. Develop and publish a project roadmap.

## Dependencies:

None.

## Acceptance Criteria

- [ ] Established location for project team documentation
- [ ] Project team guiding principles, policies, and agreements are documented in the project team location
- [ ] A roadmap is available to team members, and is accurate.

**Comment by david-waltermire-nist** [comment]
Here are a few principles that we previously discussed with regards to the metamodel development:
1. Avoid hand creation and maintenance of schema models (i.e., XML, JSON) at ALL COSTS!
2. Want to maintain all models from a single point of ground truth.
3. Published documentation must be constantly in sync with published models

This can be a start to a larger set of documented principles/decisions.

**Comment by david-waltermire-nist** [comment]
# 2018-06-07 Meeting Notes

We held a design team meeting on 6/6 to discuss this. The notes from this meeting can be found here: https://github.com/usnistgov/OSCAL/blob/feature-roadmap/source/roadmap.html.md. More work is needed to turn this into a readable draft roadmap document.

**Comment by david-waltermire-nist** [comment]
I have created an editable version of this branch here: https://github.com/david-waltermire-nist/OSCAL/tree/feature-roadmap. @akarmel please work on edits in this repo.

The roadmap file can be found here; https://github.com/david-waltermire-nist/OSCAL/blob/feature-roadmap/source/roadmap.html.md.

**Comment by akarmel** [comment]
**6/21/2018 - Sprint 11 Status Report**
- **Goal 3**: Completed updates to OSCAL roadmap - ready for review:  https://github.com/david-waltermire-nist/OSCAL/blob/feature-roadmap/source/roadmap.html.md.

**Comment by david-waltermire-nist** [comment]
Status: Waiting for review.

**Comment by iMichaela** [comment]
## Status Meeting: 8/23/2018 ##
This user story was addressed in #223 which has been reviewed and merged
