### ISSUE TITLE
Roadmap for OSCAL Tutorials

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/OSCAL#1867]
### User Story

As an OSCAL community member developing OSCAL-based software, I want to understand how to use OSCAL data formats for a simple information security lifecycle in context: who are notional actors, what do they do (in the form of relatable use cases), how do they represent OSCAL data, and when do these things in a lifecycle. I would like the examples on the updated website, and I want the example data in usnistgov/oscal-content to match up with it.

### Goals

- [x] Team to draft a roadmap that specifies:
  - [x] An approach to integrated examples that are logically connected to the tutorials, not isolated
  - [x] A simplified lifecycle based around actor-based scenario and use cases
  - ~An updated list of tutorials demonstrating their usage~
  - ~A list of recommendations after reviewing existing tutorials to recommend: keep, amend, or archive~
  - ~A list of recommendations on examples in [oscal-content/examples](https://github.com/usnistgov/oscal-content/tree/main/examples) to: keep, amend, or archive~
  - ~A list which identifies the examples embedded into _keep_ or _amend_ tutorials that are not provided as stand alone examples in [oscal-content/examples](https://github.com/usnistgov/oscal-content/tree/main/examples).~

### Dependencies

- [x] Team to review all existing tutorials.
- [x] Team to review [the 4th OSCAL Conference workshop](https://github.com/aj-stein-nist/oscal-2023-workshop)
- [x] Review of [oscal-content examples](https://github.com/usnistgov/oscal-content/tree/b940aec9fe9515184448a7e0782cfb2adb56293c/examples)

### Acceptance Criteria

- ~All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.~
- ~A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.~
- ~The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.~

(For reviewers: [The wiki has guidance](https://github.com/usnistgov/OSCAL/wiki/Issue-Review) on code review and overall issue review for completeness.)

### Revisions

I have updated and scoped down the list of acceptance criteria. Given the roadmap thus far, it seems odd to predetermine the list of tutorials and examples that need to be removed or signficantly refactored before the "inventory of OSCAL use cases" are done.

**Comment by aj-stein-nist** [comment]
@usnistgov/itl-oscal I expect anyone in the team who has opinions on the roadmap before the beginning of next week to draft a proposal here for follow-on discussion and review next week.

https://github.com/usnistgov/OSCAL/discussions/1871

**Comment by aj-stein-nist** [comment]
I drafted a provisional roadmap for discussion with the team during review:

https://hackmd.io/8ObwcnJkQzeTZfHCro6tPA?view

**Comment by iMichaela** [comment]
> I drafted a provisional roadmap for discussion with the team during review:
> 
> https://hackmd.io/8ObwcnJkQzeTZfHCro6tPA?view

@aj-stein-nist -- The HackMD file is locked for editing. Left some comments, but providing edits would be more efficient.

**Concern:** The proposed roadmap is not taking in consideration the existing tutorials and provides no proposal on how to integrate (and expand) the examples used in those tutorials, in a way that is avoiding trashing them in favor of a completely new set. Please unlock the file or advise where to capture ideas that would reuse current examples or integrate them onto the redesigned suite.
