### ISSUE TITLE
Prepare Documentation and Artifacts for Milestone 1 Release

### ISSUE THREAD

**Issue by brianrufgsa** [usnistgov/OSCAL#341]
# User Story:

As an OSCAL adopter, I need to rely on NIST-provided OSCAL resources in order to properly adopt OSCAL.

## Goals:
- Catalog and Profile documentation is accurate, complete, and up-to-date, including:
- Appropriate files are posted in appropriate locations
- Tools are available

## Dependencies:

Issue #311 #331 #332 

## Acceptance Criteria

**Catalog and Profile documentation is accurate, complete, and up-to-date, including:**

- [ ] Appropriate overview, and conceptual documentation, including ConOps and Terminology List
- [ ] Syntax-level documentation and examples
- [ ] Obsolete content is either replaced with good content or removed in all locations (do not abandon old content. Remove it.)

**Appropriate files are posted in appropriate locations**
- [ ] Especially schema and translation files
- [ ] Obsolete files are removed

**Tools are available**
- [ ] A list of tools is available, with a description for each
- [ ] Each provided tool is posed
- [ ] Each third-party tool has a clear link to its source
- [ ] Technical requirements/dependencies for tools
- [ ] Includes documentation and "Getting Started" guide
- [ ] Each tool is described, such that its intended use is clear

**Comment by iMichaela** [comment]
## 5/2/2019 ##
The team made progress, but more work is needed on the schema documentation.

**Comment by brianrufgsa** [comment]
# 5/9/2019
@brianrufgsa and @david-waltermire-nist to schedule working session next week. (Monday afternoon)

**Comment by david-waltermire-nist** [comment]
Discussed this issue with @brianrufgsa today. We came up with the following outline:

Release archive with the following contents:

- readme.txt:
  - brief into explaining what OSCAL is and pointing to the website for more info. Pointers to docs.
  - Explaining the contents.
  - How to use the resources (e.g., validate using schema, translate XML <> JSON using the XSLTs) and what tools are needed.
- content: all supporting OSCAL content
  - FedRAMP: FedRAMP profiles
  - NIST: NIST SP 800-53 content
  - (optional) demo: other examples
    - xml/json: the proceeding directories will have subdirectories corresponding to specific formats.
- template: Starter templates for use in development
- xml: All OSCAL XML support artifacts
  - schema: XML schema and schematron for each layer; flat organization
  - convert: XSLTs for json-to-xml
  - (optional) css: stylesheets for XML content authoring
  - (optional) resolve: profile resolution; current contents of util/resolve
  - (optional) publish: document generation; current contents of util/publish
- json: All OSCAL JSON support artifacts
  - schema: generated JSON schema for each layer; flat organization
  - convert: XSLTs for xml-to-json


The following is an outline of the readme.txt:

Overview
--------
- brief intro explaining what OSCAL is
  - define the OSCAL layers and how this relates to the release.
  - raise awareness of common syntax
  - Touch on the fact that XML and JSON resources are aligned, without mentioning the metaschema.
  - Summarize our CONOPS and point to the website for more detail.
- pointing to the website for more info. Pointers to docs.

Release Contents
----------------

The following contents are provided in this release:

- content
- templates
- xml
  - schema
  - convert
- json
  - schema
  - convert

This mirrors the new site layout.
  
Using OSCAL resources
---------------------
- Technical requirements for using resources

For the following, provide usage examples using open source tools:
- XML and JSON schema validation.
- XML <> JSON translation using the XSLTs

Roadmap
-------
- Discuss Next Milestones, Future Compatibility, etc.
- Point to website for more detail

How to Contribute
-----------------
- Make simple asks
- Point to github site and website for details.
- Revisit CONTRIBUTING.md to make sure it is current!

**Comment by david-waltermire-nist** [comment]
@brianrufgsa will start on the "Using OSCAL resources" and "Roadmap" sections of the readme.txt. @david-waltermire-nist will start on the rest.

**Comment by david-waltermire-nist** [comment]
## 5/16/19
The following work needs to be done still:
- We need to get the templates into the GitHub repo. @brianrufgsa has one for catalogs. Need to do the same for profiles.
- Need to build some CI/CD automation to build a tar/ZIP archives for the release.
- Need to complete the readme.txt.
- Also need to fix all the [M1 issues](https://github.com/usnistgov/OSCAL/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22OSCAL+1.0+M1%22)

**Comment by brianrufgsa** [comment]
# Using OSCAL

NIST developed the Open Security Controls Assessment Language (OSCAL) as a machine-readable data exchange format. It enables organizations to express and exchange detailed cybersecurity content in either Extensible Markup Language (XML) or JavaScript Object Notation (JSON).

NIST defined and governs the core OSCAL syntax, which includes cyber security content that is universal across industries and compliance regimes. NIST further designed OSCAL to be extended by other organizations to address industry-specific, compliance-specific, or organization-specific content. Please see the _Extending OSCAL_ section for more information.

## OSCAL Adoption

For OSCAL compliance, mechanisms interpreting or generating OSCAL content _must_ honor the core syntax described at [https://pages.nist.gov/OSCAL/docs/schemas/](https://pages.nist.gov/OSCAL/docs/schemas/).

While not mandatory, organizations adopting OSCAL are encouraged to use NIST-published validation and translation mechanisms. The validation mechanism ensures XML and JSON files are OSCAL-compliant, while the translation mechanism converts OSCAL content from either format to the other. An automated governance process enables NIST to ensure these mechanisms remain aligned with the latest OSCAL syntax.

## Standards

NIST makes validation and conversion mechanisms available using the following established standards:

|   | **OSCAL Syntax Validation**|
| --- | :---: |
| **XML** | XML Schema Definition Language (XSD) 1.1 <br /> [ [https://www.w3.org/TR/xmlschema11-1/ ](https://www.w3.org/TR/xmlschema11-1/ )] |
| **JSON** | JSON Schema, draft-07 <br /> [ [https://json-schema.org/](https://json-schema.org/) ] |

|    | **OSCAL File Conversion** |
| --- | :---: |
| **XML & JSON** | Extensible Stylesheet Language Transformation (XSLT) 3.0 <br /> [ [https://www.w3.org/TR/2017/REC-xslt-30-20170608/](https://www.w3.org/TR/2017/REC-xslt-30-20170608/)]<br /><br />XPath 3.1<br />[[https://www.w3.org/TR/xpath-31/](https://www.w3.org/TR/xpath-31/) ] |

**IMPORTANT** : XSLT 3.0 and XPath 3.1 are only required when using NIST published tools to convert OSCAL files between JSON and XML. Any version of XSLT or XPath may be used when transforming or querying OSCAL files for other reasons. Later versions offer more robust capabilities. There are several JSON query capabilities available, such as JSONPath [[https://restfulapi.net/json-jsonpath/](https://restfulapi.net/json-jsonpath/)]; however, no one capability has emerged as a clear standard as of this publication.

## Available Tools and Resources

There are many tools available to validate and manipulate XML and JSON content using these standards. This includes both open source and commercial tools, as well as standard capabilities available in many programming languages.

The following is neither an exhaustive list, nor an endorsement. OSCAL adopters are encouraged to do their own research and select the resources that are best for their specific needs and budget. OSCAL adopters are also responsible for ensuring their compliance with any licensing requirements.

In general any of these tools can provide the functionality needed to manage OSCAL files; however, when using the NIST-provided mechanisms for converting between XML and JSON, it is important to use a tool that supports at least XSLT 3.0 and XPath 3.1. Very few tools support these standards at this time.

| **Tool** | **Commercial** | **Open-Source** | **NOTES** |
| --- | --- | --- | --- |
| **oXygen XML Editor** | Yes |   | [https://www.oxygenxml.com/](https://www.oxygenxml.com/)A commercial tool with a graphical user interface for working with XML, XSLT, XSD and related capabilities. |
| **xmllint** |   | Yes | [http://xmlsoft.org/xmllint.html](http://xmlsoft.org/xmllint.html)Linux-based open source tool for XML management and manipulation.xmllint can be run on Windows with a Linux subsystem, such as |
| **Saxon-HE (Home Edition)** |   | Yes | [http://www.saxonica.com/](http://www.saxonica.com/)Saxon-HE offers the latest XSLT processing, and is fully open-source without technical support. Saxon-HE is available via [SourceForge](https://sourceforge.net/projects/saxon/files/Saxon-HE/9.9/) and Maven. It supports XSLT 3.0 and XPath 3.1.Java and .NET modules are available, which can be run from the command line or integrated into applications.Saxonica also offers Saxon PE and EE versions, which are commercial products with technical support and redistribution rights. |
| **Document Object Model (DOM)** |   | Yes | [https://www.w3.org/DOM/](https://www.w3.org/DOM/)A standard object-oriented model for manipulating XML files, which is built into many modern programming languages.DOM can manipulate XML content. Most implementations can also perform OSCAL syntax validation using OSCAL-published XSD files; however. Unfortunately, most implementations can only process XSLT and XPath 1.0 transformations, which is insufficient to use OSCAL&#39;s XSLT 3.0-based transformation files. |

# Extending OSCAL

OSCAL is designed to meet common cybersecurity information needs across multiple compliance regimes. It also provides organizations the ability to add information fields where OSCAL does not natively have an appropriate field. Always try to use a native OSCAL field first, and only extend OSCAL when no native syntax meets your organization&#39;s needs.

Extending OSCAL is accomplished through the use of &quot;prop&quot; and &quot;part&quot; elements. These may be added as child elements under any OSCAL element. &quot;prop&quot; should be used where there is one data item to represent, such as a title or date. &quot;part&quot; should be used where there is more than one piece of data that must be represented, such as an address containing street, city, state, and zip code.

Both &quot;prop&quot; and &quot;part&quot; have the following attributes available:

- @ns (required when extending OSCAL)
- @name (required when extending OSCAL)
- @class (optional –used to identify related part and prop elements)

Optionally, &quot;part&quot; elements may also use an @id attribute.

Tools that process OSCAL content are not required to interpret unrecognized OSCAL extensions; however, OSCAL-compliant tools much not modify or remove unrecognized extensions, unless there is a compelling reason to do so, such as data sensitivity.

### Best Practices and Recommendations for Extending OSCAL

Any organization that extends OSCAL should consistently assign @ns with a value that represents the organization, and then ensure each @name has a value that is unique. As a result, the combination of @ns and @name should always be unique and unambiguous, even when mixed with extensions from other organizations. @ns is required to ensure two different organizations can use the same value for @name without conflict.

For example, if FedRAMP and DoD both extend OSCAL, FedRAMP will ensure every &quot;part&quot; and &quot;prop&quot; added by FedRAMP has @ns=′fedramp′, while the DoD will ensure every &quot;part&quot; and &quot;prop&quot; added by DoD has @ns=′usdod′. If both FedRAMP and DoD need to add a status field for different reasons, there would be no conflict because:

- the FedRAMP extension would look like this:
\&lt;part ns=′fedramp′ name=′status′\&gt;Something FedRAMP Cares About\&lt;/part\&gt;
- while the DoD extension would look like this:
\&lt;part ns=′usdod′ name=′status′\&gt;Something DoD Cares About\&lt;/part\&gt;

Each organization is responsible for governance of their extensions, and is strongly encouraged to publish their extensions as standards to their user community. In the example above, FedRAMP is responsible for ensuring consistent use of @name values everyplace @ns=′fedramp′ exists. Similarly, DoD is responsible for ensuring consistent use of @name values everyplace @ns=′usdod′ exists.

**Comment by brianrufgsa** [comment]
@david-waltermire-nist the above content is ready for review.

**Comment by david-waltermire-nist** [comment]
@brianrufgsa I like the content, but I think most of it would be better placed on the site and in the repo. I started PR  #416 to do this work. Checkout the [new XML documentation](https://github.com/usnistgov/OSCAL/blob/7cc79fe604f894ff7c32623144229ca500d13e20/xml/README.md) to see what I am thinking.

I'd appreciate any thoughts you have on this (partial, work-in-progress) approach.

**Comment by wendellpiez** [comment]
I would also be willing to pitch in and add some useful hooks and pointers.

**Comment by david-waltermire-nist** [comment]
PR #421 also adds a "download" page to the OSCAL website. This PR will be pulled after the release is made.
