### ISSUE TITLE
[EPIC] Metaschema enhancments to support OSCAL modeling

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/OSCAL#595]
# User Story:

As an OSCAL model developer, I need to take advantage of a number of metaschema enhancements. This epic tracks a set of metaschema enhancements that have been planned.

## Goals:

The following issues need to be completed:

- [x] Complete coverage of JSON Schema production unit tests (usnistgov/metaschema#18)
- [x] Move Metaschema documentation and code to a new GitHub Repository (#596)
- [ ] Support valid OSCAL fragments (#590)

## Dependencies:

None.

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by david-waltermire-nist** [comment]
I am going to close this epic since the metaschema portions are completed. We will continue work on issue #590.
