### ISSUE TITLE
[EPIC] Development of OSCAL Tooling

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/OSCAL#598]
# User Story:

As an OSCAL user, I need a set of tools that help me perform common actions on OSCAL content. These actions include:
- Validating an OSCAL content instance against the appropriate schema/schematron
- Performing Profile resolution of an OSCAL Profile
- Producing renderings of OSCAL content (e.g., Catalog, Profile, SSP) in human-readable formats (e.g., HTM, PDF)

As an OSCAL tool developer, I need readily available programing language specific data APIs that help me to load and save OSCAL content in XML, JSON, and YAML formats. These data APIs will save me time in writing tooling, allowing me to focus more immediately on the business logic of the tool.

## Goals:

- [ ] Produce a simple, command line tool that supports: (usnistgov/oscal-tools#3)
    - [ ] Validating an OSCAL content instance
    - [ ] Converting an OSCAL content instance between XML, JSON, and YAML formats.
    - [ ] Renders an OSCAL content instance into human-readable formats
- [ ] Develop programing language specific data APIs capable of loading and saving OSCAL content to and from programing language specific data structures. (usnistgov/metaschema#20)

## Dependencies:

None.

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by bradh** [comment]
Can you say more about what from usnistgov/metaschema#20 relates to this? The repo is (apparently) private - I can't see the issue.

**Comment by aj-stein-nist** [comment]
It appears this work has been completed in large part before and this issue is obsolete. Closing it for now.
