### ISSUE TITLE
[EPIC] Write OSCAL content creation tutorials

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/OSCAL#599]
# User Story:

As an OSCAL content creator, I need to understand how to create OSCAL content by hand. This will help me create content until suitable content creation tools exist for me to use.

## Goals:

Create a series of tutorials covering content creation topics.

Each tutorial will need to provide:
- An explanation of what prerequisite knowledge the reader must have.
- Information about any tools needed for the tutorial, including how to download, install, and use the tool.
- A brief discussion of the OSCAL concepts, including pointers to the OSCAL [documentation pages](https://pages.nist.gov/OSCAL/documentation/) for more information.
- A step-by-step walkthrough explaining how to create the different parts of the OSCAL content. Each step should include examples in XML, JSON, and YAML.
- A full completed example at the end of the tutorial in XML, JSON, and YAML.

Initial tutorials will include:

- [ ] Creating a basic OSCAL catalog (#592)
- [ ] Creating a basic OSCAL profile (#593)
- [ ] Creating a basic OSCAL system security plan (#594)

Other tutorials may address #567, #572.

## Dependencies:

- A simple tool is needed to provide for validation capabilities. (usnistgov/oscal-tools#3) 

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by david-waltermire-nist** [comment]
Issue #293 previously identified this work. Closing the old one in favor of this issue.
