### ISSUE TITLE
Tracker Issue for Oscal-Deep-Diff Work

### ISSUE THREAD

**Issue by nikitawootten-nist** [usnistgov/OSCAL#687]
# User Story:

As an OSCAL stakeholder, I need to be able to understand the differences between revisions of an OSCAL document.

## Goals:

This is a tracker issue for the [usnistgov/oscal-deep-diff](https://github.com/usnistgov/oscal-deep-diff) repository. The following is a list of features to be completed before the repository is considered 'minimally viable':

- [ ] Meta-enhancements to the repo
    - [ ] usnistgov/oscal-deep-diff#1 - Circle CI
    - [ ] usnistgov/oscal-deep-diff#2- Repo templates for community involvement
- [ ] usnistgov/oscal-deep-diff#3 - Documentation and defined schema structure for output
- [ ] usnistgov/oscal-deep-diff#4 - Improve and test optimal match scoring system
- [ ] usnistgov/oscal-deep-diff#6 - Tool allows for constraints on matching behavior (tune tool to work best for OSCAL documents)
- [ ] Stretch Goals
    - [ ] usnistgov/oscal-deep-diff#4 - Optimization work

## Dependencies:

None.

## Acceptance Criteria

The tool is clear and easy to use, works, and well tested, with clear criteria for community improvement.

## Additional Information

Contact @nikitawootten-nist for any additional questions

**Comment by nikitawootten-nist** [comment]
# Update 6/11/2020
A lot of progress this week:
- Most of the work this week has been on usnistgov/oscal-deep-diff#6. Custom constraints have been implemented, but not the configuration/deserialization step to load them yet.
- Had a call with @david-waltermire-nist on CircleCI integration, and I set up a basic CircleCI test and set up a sensible configuration for when to run the build and test job. In the future, once this project is set to be a library, additional configuration will be needed to automatically push artifacts to NPM.
- Next week I will focus on finishing usnistgov/oscal-deep-diff#6 as well as usnistgov/oscal-deep-diff#4, since adjusting constraints changed scoring criteria.

**Comment by nikitawootten-nist** [comment]
## Update 7/9/2020
Over the past few weeks I've made many changes.
- Testing was taking too long, so I made the optimization changes that I initially planned on doing at the end. This drastically cuts down on runtime.
- As per our sprint conversation two weeks ago, I have updated the match by property constraint to work on sub-object's properties. Meaning, two objects in an array can be matched using a property that they both share, even if that property is nested within a sub-object.
- The ability to ignore certain objects has been implemented.
- Work still remains in documentation, tuning, and loading/parsing of constraints.

**Comment by nikitawootten-nist** [comment]
## Update 8/12/2020
I haven't been updating this tracker issue for a while, but since the last update most goals were implemented. During the last meeting a discussion regarding a human-readable output mode and a bug with my CircleCI workflow. Issues have been created on the oscal-deep-diff repo and new tasks have been added to this tracker issue.
