### ISSUE TITLE
Updates to SP800-53 Rev5 conversion/production pipeline to Milestone 3 models

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#690]
# User Story:

Some recent changes to models such as producing UUIDs in catalog metadata and back matter require updates in the pipeline that converts NVD XML (produced from upstream sources) into OSCAL for this data.

The data currently being distributed was updated with a maintenance transformation (in the `src/release/content-upgrade` directory); the same capability must be integrated into the pipeline.

## Goals:

1. Enable short rampup for any new release of SP800-53 data by keeping conversion scripts and stylesheets up to date
1. Incrementally improve the data set in its OSCAL representation (with #672) 
1. (With #672) collect information on patterns and anomalies to feed back upstream (both NVD production and FISMA team) 

## Dependencies:

This code is maintained in an internal repository here: https://gitlab.nist.gov/gitlab/oscal/oscal-tools. It could also use more documentation.

#672 has an end-to-end dependency on this Issue, as its pipeline must also provide valid data.

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] Pull Requests (PRs) are submitted to two repositories as applicable, which together fully address the goals of this User Story. This issue is referenced in the PRs.
  - [ ] An updated and improved OSCAL version of the (FPD or current) Rev 5 valid to current OSCAL models is available in the OSCAL repo
  - [ ] Conversion tooling is updated in the internal repository where it is maintained
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by wendellpiez** [comment]
**Update Sep 23 2020**

Addressed this with https://github.com/usnistgov/oscal-content/issues/15 (formerly #672).
