### ISSUE TITLE
Update Website Content [EPIC]

### ISSUE THREAD

**Issue by brian-ruf** [usnistgov/OSCAL#706]
# User Story:

As an OSCAL practitioner, I need to rely on the content at [https://pages.nist.gov/OSCAL/documentation](https://pages.nist.gov/OSCAL/documentation) for understanding the OSCAL layers and models. This includes important concepts for each layer, as well as the relationship between layers.

Content for early layers exists, but must be updated to reflect recent changes, or augmented to meet the goals below. Content for newer layers is sparse and must be developed.

## Goals:

For each model, provide the following content:
- **Purpose**
  - What is the significance? 
  - What does it do for OSCAL users?
- **User Base** 
  - Who typically authors this model? 
  - Who typically consumes this model?
- **Core Concepts**
  - What are the core concepts for this model?
- **Organization**
  - How is the model organized?
- **Relationships**
  - How do the layers and models relate to other layers and models? 
  - What other models consumes this model?
  - What models are consumed by this model?
- **Walk Through**
  - A brief/high-level tutorial for this model

For each layer, provide a summary of the models in that layer based on the above content.

## Dependencies:

- Catalog Layer and Model: Issue #707 
- Profile Layer and Models Issue #708
- Implementation Layer and Models: Issue #709
- Assessment Layer and Models: Issue #710 (Merging in #646 )
- Assessment Results Layer and Models: Issue #711

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

- [ ] Catalog Layer Content Complete
- [ ] Profile Layer Content Complete
- [ ] Implementation Layer Content Complete
- [ ] Assessment Layer Content Complete
- [ ] Assessment Results Layer Content Complete

**Comment by david-waltermire-nist** [comment]
This was addressed in PR #748 and later commits.
