### ISSUE TITLE
EPIC: Update Profile Resolution Specification

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/OSCAL#954]
# Describe the bug

The OSCAL [profile resolution specitication](https://pages.nist.gov/OSCAL/concepts/processing/profile-resolution/) is out of date and needs to be updated.

There are a few additional issues that relate to this:

- [ ] Checking if the profile-resolution files provided take into account the merge/custom function (#897)
- [ ] Profile: identifier specificity when multiple catalogs are imported (#843)
- [ ] target examples in Profile Resolution selection and merge phase documentation (#740)
- [ ] Profiles when resolved should show their provenance (#680)
- [ ] How to handle profile resolution title addition? (#579)
- [ ] Tracking control identity via catalog of origin (#538)

Updates to the profile resolution specification must:
- [ ] Address the issues above.
- [ ] Provide clear processing narrative for a tool implementer focused on XML, JSON, and/or YAML.
- [ ] Be consistent with the current OSCAL models.
- [ ] Any changes and clarifications should be presented and reviewed during the OSCAL model review,

# Who is the bug affecting?

Anyone implementing profile resolution.

# What is affected by this bug?

The current specification is not completely accurate and will lead to improper implementations.

**Comment by ohsh6o** [comment]
Is this the issue we should provide feedback on @stephenbanghart's excellent presentation today or elsewhere?
