### ISSUE TITLE
Tracker Issue for OSCAL-deep-diff Control Level Comparisons

### ISSUE THREAD

**Issue by nikitawootten-nist** [usnistgov/OSCAL#988]
# User Story:

As an OSCAL catalog consumer, I need to compare revisions of OSCAL documents with respect to individual controls in order to find changes to controls that have high, medium, or low impact.

## Goals:

This is a **tracker issue** for [usnistgov/oscal-deep-diff](https://github.com/usnistgov/oscal-deep-diff). The following is a collection of features that need to be implemented in order for control-level-comparisons to be minimally viable.

### Old issues
- [X]  usnistgov/oscal-deep-diff#22
    - [X] Explicitly prevent matching or comparing certain properties
    - [X] Operation to flatten list of subtrees into one large list for comparison
- [X]  usnistgov/oscal-deep-diff#19 
    - [X] YAML configuration
    - [X] Create "Tracked" array/object/primitive wrapper that keeps track of the pointer
- [X] Fix out-of-tree and base comparison operations to handle unmatched elements (no corresponding issue)
- [x] usnistgov/oscal-deep-diff#27
- [x] usnistgov/oscal-deep-diff#28
- [x] usnistgov/oscal-deep-diff#29

### To complete:
- [x] usnistgov/oscal-deep-diff#31
- [x] usnistgov/oscal-deep-diff#32
- [x] usnistgov/oscal-deep-diff#33

## Dependencies:

This Epic depends on #687, the base requirements for [usnistgov/oscal-deep-diff](https://github.com/usnistgov/oscal-deep-diff).

## Acceptance Criteria

- [x] The tool produces clear control-level-comparison documents in a format that is human-readable
- [x] The tool is well documented so that even those who may not have a good understanding of Typescript can use it
- [x] The tool has well-tested examples

## Additional Information
Contact @nikitawootten-nist for any additional questions.

**Comment by nikitawootten-nist** [comment]
## Update 7/29/2021
As of today, the control level comparison intermediate document draft has been fully implemented, and the capabilities to generate a human-readable spreadsheet based on the intermediate document has been added. This output spreadsheet, like the intermediate document it is based on, is subject to change.

The output spreadsheet has two pages:
1. A list of all controls, their old and new identifiers, a `status` column (`ok` (unchanged), `added`, `withdrawn`, or `changed`), the number of changes, and the identifiers of a given control's parent (if the control has been moved)
2. A list of changes corresponding to a given control, including the name of the field that has been changed, `the status of that change (`added`, `withdrawn`, or `changed`), and the raw old and new field values.

This output document has a few issues that need to be worked out:
- The order of controls and groups is not preserved in the initial diff. The workaround I've taken so far is to simply sort the controls by `id`, but this sorting needs to be improved (e.g. `ac-11` should not come before `ac-2`)
- The change details are only readable when an individual field has been changed. When a sub-object (such as a property) has been added or removed, the change is represented by a json string of the sub-object, which is not very readable.
- The change details `field` column may be confusing to those without experience in json, and an alternate representation where array objects are represented by some identifier rather then an array index may be required. (e.g. instead of `parts/2` being listed as "added" to `ac-1`, name the field `parts/ac-1_obj`)
